holepunchto/hyperdrive

README.md
I wasn't able to figure out what `link` and `hash` should be but I was able to finish a lot more of the code in the Usage part of the readme
=> Complete example code in Readme

SPECIFICATION.md
I fixed some grammar issues, and added a few style changes to improve clarity of some of the sentences.  
I also have a few comments on sections where the fix wasn't obvious. I'll add those in as inline comments.
=> More style and grammatical suggestions.

SPECIFICATION.md
These are the fixes from the inline discussions in https://github.com/mafintosh/hyperdrive/pull/10.
I'll open a reminder issue for the only thing I wasn't able to take care of.
EDIT:  Okay, here is that issue: https://github.com/mafintosh/hyperdrive/issues/12
=> spec fixes

README.md, index.js
=> Add stats object to Archive for progress reasons

index.js
Fixes #32 and emits events for empty things.
=> Add download events for createEmptyEntry + Bug Fix

README.md
=> Change readme example to use discovery-swarm

index.js, package.json
Borrowed this code from tar-fs, should we put normalize.js into a different module? Ideas on a name?
=> Normalize windows filenames upon append

package.json, test/rw.js
I would expect these two test cases to be able to read from a record that I just wrote, but instead I don't get any data.
=> failing tests for write/read streams

archive.js, cursor.js, test/rw.js
Squashed all the commits from #60, but did it on a separate branch. Take two!
=> added createByteCursor for random-access reads

README.md
Hi, first time hyperdrive user here.
Based on my experience trying hyperdrive, here's my attempt to make the example in `README.md` easier to follow.
1. The `'another-hyperdrive.db'` example led me to think it's in another file. However, it should be put right after the `archive.finalize` part, so I merged them together.
2. Copy-paste and you're ready to go. Better experience for anyone just trying out.
Any comment is appreciated :)
=> Make example in README.md easier to follow

README.md, archive.js, test/misc.js, test/overwrite.js
* Live by default
* document `archive.live`
=> make live default and add live docs (#72, #77)

README.md
Update the readme to include the sparse-mode option
=> document the sparse-mode option

archive.js, test/replicates.js
=> Force writing empty file.

archive.js, package.json, storage.js, test/misc.js
i'm totally not sure this is the proper way to implement this...
=> preserve utimes

README.md
update `README.md` based on https://github.com/mafintosh/hyperdrive/issues/100
=> add note about finalize on unowned archive in README.md

index.js, test/storage.js
otherwise those are uncatchable
=> forward .metadata errors

README.md
Thanks for bringing this to my attention @mafintosh. It was really useful.
=> Update documentation to include information about readDir cache option.

README.md, index.js
Depends on https://github.com/mafintosh/hypercore/pull/104
=> Pass replication opts to hypercore

index.js
Closes https://github.com/mafintosh/hyperdrive/issues/172
=> Fix exception-throwing edgecase in createReadStream

test/basic.js, test/storage.js
=> add test for using sparse and createReadStream

index.js
Closes https://github.com/mafintosh/hyperdrive/issues/181
=> Content hypercore options

index.js
Tests remain unchanged and pass. Fixes #183
=> remove legacy version setter

README.md, index.js
Changes based on: https://github.com/mafintosh/hyperdrive/issues/188
=> add sparseMetadata option

README.md, index.js
I think this works.
But before merging I will also add some text to the docs.
=> add cached option to readFile and createReadStream

index.js
If registering for 'error' is delayed then in some cases (such as the "Key and secret do not match") the listener is registered too late and the app doesn't get a chance to handle it (it throws toplevel).
This PR makes sure that hyperdrive catches and bubbles the event.
=> Immediately register content hypercore error event

index.js
so you can use `ram` with file storage, etc.
=> Support other storage for content metadata

README.md
=> Readme.md typo fix

README.md, lib/messages.js, lib/stat.js, schema.proto, test/stat.js
This allows to add metadata to Stat entries. See the test for an example. 
(This PR is against the v10 branch)
=> Allow to add metadata to Stat entries

index.js, test/basic.js
depends on https://github.com/andrewosh/hypercore-byte-stream/pull/3, cc @andrewosh
=> V10 less seeky

lib/fd.js, test/fd.js
fixes an issue with certain parallel reads from an fd
=> fd parallel read fix

README.md, index.js
This'll fix https://github.com/datproject/sdk/issues/41
=> Added peer-add and peer-removed events

package.json
=> Fix mountable-hypertrie min version

README.md, index.js, promises.js, test/mount.js
This adds an `info` method which will return mount information about a file (and potentially other information that doesn't fit nicely into a Stat object in the future).
=> Add info method

README.md
Just a bit of housekeeping on the `README`
=> Updated Hypercore repo links

README.md
Also clarified that the update event doesn't get emitted unless you're watching files or downloading data.
=> Add docs for drive.watch

index.js
=> Fix for "expected string" error in later Fixname call, Issue #309

index.js, package.json, test.js
Depends on https://github.com/holepunchto/corestore/pull/54
=> Support new writable option from Corestore

README.md, index.js, test.js
Should be similar or very "interoperable" with https://github.com/holepunchto/localdrive/pull/25
=> Add drive.compare(entryA, entryB)
