holepunchto/hyperdrive

- package.json
Just adding pump depends so `npm run bundle` works
> add missing pump depends

- lib/protocol.js
This will make it easier to rename the protocol to hypercore later.
I'm basing this change on the assumption that eventually hyperdrive is supposed to depend on hypercore, which I'm not sure is true, so this pull request may be misguided.
> Allow "hypercore" as a valid protocol value

- index.js
Thanks for implementing the other stats progress. There was one bug, the bytesRead for a *single append* was stuck at 0, not updating. Currently only the total bytes read is updated (`Archive.stats.bytesRead`). 
This is one way to fix it but there may be a better way to do it.
> bytesRead progress for single append doesn't currently update

- index.js
- test/replicates.js
Fixes empty file and directory bug (#28)
I added one test for the empty file. I was having trouble testing the empty directory issue though - can you run `appendFile` on a directory somehow?
> Copy empty folders and files (#28)

- README.md
Addresses issue #33: 
* Adds docs for `archive.lookup` function
* Adds docs for progress events
* Updates `archive.download` and `archive.appendFile` to include progress
> Add docs for lookup and progress (#33)

- README.md
The `archive.download` docs only described the `index` first argument, but actually it can be either an index or an `entry`
> Update archive.download docs to match args

- test/overwrite.js
Here is a failing test for overwriting a file derived from https://gist.github.com/substack/20e0ed68b82b288f20d0380233cf27b4
I'm not sure why but the `createFileReadStream()` calls also hang.
> failing overwrite test

- README.md
- archive.js
- test/misc.js
This patch allows `archive.list()` to accept an `opts.offset` parameter instead of the default value of `0`. This way, I can more easily write a hyperdrive indexer that tails the internal feed without having to implement the machinery already defined in `.list()`.
> list() offset

- archive.js
- test/misc.js
When a new entry is added to an archive, the `content` field of the entry message is populated with that entry's `bytesOffset` and `blockOffset` -- just pulled from the the hypercore on insertion. 
Added a few tests for archives containing one and two files in `test/misc.js`.
> Adding entry.content with bytesOffset and blockOffet

- archive.js
- cursor.js
- test/rw.js
This PR changes createByteCursor into a synchronous call that will asynchronously get an entry out of the archive the first time `next()` is called.
@mafintosh this look better? It's certainly been easier to work with so far.
> make createByteCursor synchronous

- test/replicates.js
Adds (currently failing) tests for downloading empty file/directory to file system. #28
> add tests for downloading empty file/dir to fs

- archive.js
- test/rw.js
This patch skips the extra recursive lookup in `_range()` for objects which are already entries. This means methods that use `_range` such as `createFileReadStream()` can stream the data from previous documents, not only the latest document.
> skip extra entry lookups in _range

- README.md
- archive.js
- test/misc.js
Closes #97 and adds 2 new methods. From the readme:
---
Count the number of blocks in the entry that have been downloaded.
You can calculate the file's download progress, as a percentage, with:
```js
var downloaded = archive.countDownloadedBlocks(entry)
var progress =  downloaded / entry.blocks
```
Has all of the entry's blocks been downloaded?
> Add archive.countDownloadedBlocks and archive.isEntryDownloaded

- README.md
```
var live = opts.live === false ? false : (opts.live || !cb)
```
archive.list() have different default for `live` option based on callback is given or not
- `archive.list(cb)` : `live` is false
- `var rs = archive.list()` : `live` is true
> Fix doc about default value of live of archive.list()

- README.md
The stream is optional in unreplicate
> Fix unreplicate documentation

- README.md
- archive.js
- test/misc.js
Hypercore feeds can be passed to `createArchive` as `metadata` and `content` options.
The test is pretty basic. Let me know if there is other things that would be good to test here.
> allow feeds to be passed to createArchive directly

- archive.js
- storage.js
adds `file(name, archiveOptions, seq)`
> pass metadata block seq to .file

- test/replicates.js
Adds two tests, one of them is failing (the one that uses `raf` options for the length stuff).
> add replicate test with file updates

- archive.js
`_selectLatest` keeps trying to download stuff even after the archive is closed. This is causing lots of seg faults when we try to close things. 
PR makes sure we stop loops if archive is closed.
> stop selectLatest if archive is closed

- archive.js
`_onlyLatest` should always be false for archive owners. 
I think this was another cause of some of our source corruption. If not, it'll at least avoid a bunch of download requests overhead.
Sometimes owners will still use `opts.file` (for example if you want to do `archive.append`, its required).
> only set latest for downloaders

- archive.js
- test/misc.js
The hyperdrive ecosystem doesnt enforce whether there should be a preceding slash on file entries in the metadata stream. This means that lookups can sometimes fail because of different policies on preceding slashes. This PR fixes that in lookup().
(Solves a problem in bkr)
> Normalize paths on lookup()

- archive.js
- test/replicates.js
Right now `sparse` doesn't work if the `file` option is also set because `_selectLatest` gets called. PR adds a test and fix.
* Adds a test using both `opts.sparse: true` and `opts.file`
* Set `_onlyLatest` to false if sparse is true
> Fix sparse archive option with file option

- package.json
- test/storage.js
* Add a [failing test](https://github.com/mafintosh/hyperdrive/compare/master...joehand:secret-key-test?expand=1#diff-6a1112979275ee9654c3b1f5a4c15c2dR16) for secret key bug
* Also adds a few basic storage tests
Not sure how best to *resume* an existing archive with v8 API, but this seems to work =). Passing secret key in https://github.com/mafintosh/hyperdrive/blob/master/index.js#L393-L395 fixes bug + passes test.
> add storage tests for secret key bug

- index.js
- test/storage.js
* Fix bug missing self in `self.tree` variable to set version for existing feeds
* Add `version = -1` fix for existing archives
* Add version tests to storage test
> Fix archive.version for resumed archives

- README.md
Based on some errors I just got, it looks like including the original archive's key is required for replication
> Readme: Add origKey to replicate example

- index.js
Adds `opts.indexing` to the content feed. 
It didn't seem like this should be added to metadata feed, is that correct?
> add indexing to content feed

- index.js
When replicating to a browser via websockets and storing in indexedDB, performance isn't the best.  It would be nice if the metadata could be sparsely replicated in addition to the content.
> Pass sparse flag to metadata as well as content hypercore

- README.md
- index.js
- lib/cursor.js
- lib/stat.js
- test/cursor.js
WIP, opened now so people can follow along and give feedback
> Support .open, .read and a high level file cursor api

- README.md
- index.js
- test/basic.js
Depends on https://github.com/mafintosh/append-tree/pull/10 and https://github.com/mafintosh/hypercore/pull/124
Adds `{metaStorageCacheSize: 65536, contentStorageCacheSize: 65536, treeCacheSize: 65536}` opts to the constructor
> Add cache-size opts

- index.js
Useful for apps that need to generate the keypair ahead of time.
> Pass secretKey option to hyperdb

- index.js
The existing code doesn't return a value when there is more than one
choice.
This fixes the issue where data would 'disappear' on ttps://dat-multiwriter-web.glitch.me/ when two writers make the same change at the same time.
> Pick a version when there are conflicts

- README.md
- index.js
Makes it possible to
```js
archive.stat('/', {wait: true}, cb)
```
and/or
```js
archive.stat('/', {cached: true}, cb)
```
They actually have different effects. `cached=true` seems to succeed if the data isnt available if the block represents a folder, while `wait=false` will error no matter what.
> Add cached and wait opts to stat, lstat, access, and exists

- README.md
- index.js
Add options to `checkout()` to configure the new instance
```js
// example
archive.checkout(version, {
metadataStorageCacheSize: 0,
contentStorageCacheSize: 0,
treeCacheSize: 2048
})
```
> Add options to checkout()

- index.js
- lib/fd.js
This PR fixes a strange FUSE bug on OSX (`getattr` and `write` get called concurrently, to devastating effect...).
> Update FD size during write

- index.js
Allows the content feed to be passed in constructor. This allows consumers to control the content feed without extra wrestling with hyperdrive internals.
I'm relying on this for kappa-core multiwriter hyperdrive https://github.com/karissa/peerfs
You *used* to be able to do this last time I checked (2 years ago??) and there is some code hanging around that allows it, I think this just got accidentally overlooked.
> fix: allow content feed to be passed in constructor

- README.md
- index.js
- package.json
- test/extensions.js
Following up on [the hypercore extension support](https://github.com/mafintosh/hypercore/pull/214), this surfaces the extensions API in hyperdrive so that applications can build on top of it.
This could simplify code for things like Beaker's [datPeers](https://beakerbrowser.com/docs/apis/experimental-datpeers) API.
Adds:
- `extensions` option in constructor that gets passed to the metadata hypercore
- `extension` method for sending an extension message to all peers
TODO:
Should I maybe redo this PR against the v10 branch, or could we get it into a v9 release before then?
> Added extension support

- README.md
- index.js
- test/basic.js
It can be a little frustrating to manage hyperdrives (for example in the SDK) when you don't know when an application will be closing them.
This PR propagates the `close` event from the metadata hypercore to the hyperdrive.
> Emit close event on archive close

- README.md
- index.js
- test/basic.js
- test/extensions.js
Adds the following:
- Added `extensions` array to constructor to be passed down to the metadata core
- `"extension"` event from the metadata feed to listen on extension messages
- `extension()` method for broadcasting extension messages to peers
- `.peers` getter for getting the current list of peers (useful for stuff like getting the health of an archive)
- `"peer-add"` event from the metadata feed so that actions can be taken when a peer is added (useful for extension stuff)
- `"peer-remove"` event from the metadata feed so that actions can be taken when a peer is removed
- `"close"` event so that actions can be taken when the archive is closed (useful for the SDK)
- docs for the `"update"` event so that people can be aware of it
Ideally these properties and events should be exposed in …
> Added events and docs

- index.js
- test/diff.js
This adds the seq numbers to the diffstream. The data is already there from hypertrie's diff method but not exposed currently. It's great to have for all kinds of kappa-style secondary indexes, and I don't see a reason not to have it if its there already.
> Add seqs to diffStream entries

- index.js
- lib/iterator.js
`path-browserify` does not provide a `.posix` implementation.
Environments without a posix implementation should just use the native implementation.
> Fix path.posix not being available in browsers

- lib/fd.js
- test/fd.js
When a file descriptor is closed, it should cancel all pending download ranges, which should in turn trigger cancellation errors for all pending reads. This is particularly important for FUSE, as it will prevent hanging terminals etc after a program exits before reads could complete.
> FD close cancels pending reads

- index.js
The metadata/content feeds might not be closed when the drive is closed (they might be mounted elsewhere, or being passively replicated in the corestore). If we don't remove these listeners, the drive state will be leaked after close.
> Remove listeners on close

- index.js
- lib/iterator.js
- test/download.js
Right now `download` is used to download the latest versions of specific files/directories within a drive. It'd be possible to extend this to support downloading all previous versions of those files/directories as well, but doing so might complicate the usage (i.e. `drive.download('/my-directory', { allVersions: true})`.
The UX there gets even trickier when considering mounts. What if `/my-directory` was previously a mount? It can get hard to reason about.
This PR adds a `mirror` method that does a full sync of a drive's metadata/content at the Hypercore level. It currently syncs all mounts as well, but this can be made configurable in the future. 
Any thoughts on introducing an additional method for this behavior?
> Adding a mirror method

- README.md
- index.js
This was added in the latest hypercore to signal handshaking being completed and is important for extensions to work properly.
Goes along side `peer-add` and `peer-remove`
> Added peer-open event

- README.md
- index.js
Removed old extension APIs from docs, but left the code in.
This should give us parity with how extensions work in hypercore.
> Expose registerExtension API

- index.js
- test/clear.js
Fixes https://github.com/hypercore-protocol/hyperdrive/issues/228#issuecomment-668678754
This calls `clear` under the hood for the given file, using the same walking tree as the hyperdrive.download function. 
If this is a desired appraoch, I will also write a companion section for the README and tests for directories/mounts
> feat: .clear a file from local cache

- index.js
Adds support for the `headerType` option to track the `type` in the hypercore header.
Fixes #294
> Add headerType, defaults to hyperdrive

- index.js
- test/storage.js
At the moment content feeds aren't using corestore's namespace feature for deriving their private key. This makes backups a little harder since you need to keep track of both keypairs and need some way of injecting both private keys into the hyperdrive (only the metadata one is easy it seems).
This change uses corestore's `namespace` feature to derive the private key of the content feed based on the key of the metadata feed and some extra text.
With this in place, hyperdrives are generated more predictably, and hyperdrives generated with a name can be re-generated on other devices for backup restoration purposes.
Does this approach make sense? Wanted to get a bit of review before I added unit tests and docs.
> Use name when generating content feed

- test/mount.js
Is L879 supposed to be d2 (and not d1, since d1 is not defined in this function)?
> L879 d1 supposed to be d2 ?

- index.js
pumpify was imported twice with two different names. removing the unused import
> remove duplicate import

- README.md
- index.js
- test/helpers/create.js
Remains backwards-compat with function-call instantiation.
See https://github.com/hypercore-protocol/hyperbee/pull/19 for history
> Change to 'new' constructor pattern 

- README.md
- index.js
Listens for uploads and downloads in metadata and content and re-emits.
This is useful for apps that want to listen for changes in download progress without having to mess around with drive internals.
> Add metadata-download/upload and content-download/upload events

- index.js
- test.js
Clearing on a checkout does not currently work, because `_open` on a checkout doesn't eagerly open the blobs (causing `clear` to short-circuit). Let me know if I'm misunderstanding the reasoning for that.
The first commit in this PR is the failing test, and the second is the fix.
> Fix checkout clear bug

- index.js
- test.js
Currently a new blobs core session is created whenever a new batch is created, but they are never closed. This PR always closes the blobs core of a batch.
> Fix blobs session leak on batching

- README.md
- index.js
- package.json
- test.js
Rebased from external Hans's branch to debug a bit
> Remove files sub

- index.js
Relevant to be able to do things like `await drive.get('./file', { wait: false })`, so you only get the file if it's locally available
> Let get pass forward opts

- test.js
Cleans up the test for 'drive.get(path, { wait: false }) throws if entry exists but not found', and closes the drives for all tests
> close drives in teardown

- .github/workflows/test-node.yaml
Also fixes the commit hashes for the external actions we use, as recommended by github to protect against supply-chain attacks
> Trigger canary when releasing a new version

- index.js
- test.js
- Ensure the drive is ready
- Throw when truncating future version (previous behaviour was to hang on `getBlobsLength`, before reaching the bad-argument check)
> Clean up truncate

- index.js
- test.js
This PR adds a static method that returns the primary key of a Hyperdrive for a corestore instance.
> add get db key as a static method

- README.md
- index.js
- test.js
This PR adds `ignore` option to `list`. This mirrors the behavior of [localdrive list `ignore`](https://github.com/holepunchto/localdrive/commit/99d2d63d0652fd3db97ac6c2f57b78d9f55f6e69).
> add ignore option to list

- index.js
- lib/monitor.js
- package.json
- test.js
Example usage:
```javascript
const monitor = drive.monitor(file)
await monitor.ready()
monitor.on('update', () => {
// object of upload/download stats, updated on each block
console.log(monitor.uploadStats)
console.log(monitor.downloadStats)
})
```
> Add monitor

- README.md
- index.js
- test.js
Use case: 
we have a key from hd running remotely and create new instance with local corestore
````
const drive = new Hyperdrive(store, key)
...
drive.download('/')
```
and tomorrow we do again
```
const drive = new Hyperdrive(store, key)
```
need a quick way to check if files already available locally ( and let user know).
> feat: has method implementation

- test.js
Without the checkout, occasionally (~1/200 runs) the `entry` call runs on a drive with version 1 instead of 2, causing it to return null.
> Fix flaky test: ensure it uses the correct length
